version: "3"

services:
  web:
    build: ./app
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  nginx:
    build: ./frontend
    ports:
      - 443:443
    depends_on:
      - web
    # For dev
    volumes:
      - ./frontend/static:/static

volumes:
  postgres_data:
