# Generated by Django 5.0.3 on 2024-03-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0002_deneme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Deneme',
        ),
        migrations.AddField(
            model_name='stats',
            name='amilla',
            field=models.CharField(default='Amilla', max_length=50),
        ),
    ]
