# Generated by Django 5.0.3 on 2024-03-17 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0004_remove_stats_amilla_stats_istournamet_stats_player_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='player',
            field=models.JSONField(auto_created=True, default=dict),
        ),
    ]
