# Generated by Django 5.0.3 on 2024-03-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0005_alter_stats_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='isTournamet',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='stats',
            name='player',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='stats',
            name='winning_player',
            field=models.CharField(),
        ),
    ]
