# Generated by Django 5.0.3 on 2024-03-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0006_alter_stats_istournamet_alter_stats_player_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='user',
            field=models.CharField(default='nouser'),
            preserve_default=False,
        ),
    ]
