# Generated by Django 5.0.3 on 2024-03-17 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0007_stats_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stats',
            old_name='player',
            new_name='players',
        ),
    ]
